[build]
  functions = "functions"
[context.dev]
  NODE_ENV = "development"
  environment = {TIGRIS_URI = "localhost:8081", TIGRIS_CLIENT_ID = "", TIGRIS_CLIENT_SECRET = ""}
[template.environment]
  TIGRIS_URI = "change me for your tigris uri"
  TIGRIS_CLIENT_ID = "change me for your tigris client id"
  TIGRIS_CLIENT_SECRET = "change me for your tigris client secret"  
