[build]
  functions = "functions"
[context.dev]
  NODE_ENV = "development"
  environment = {TIGRIS_URI = "localhost:8081"}
[template.environment]
  TIGRIS_URI = "api.preview.tigrisdata.cloud"
  TIGRIS_CLIENT_ID = "change me for your tigris client id"
  TIGRIS_CLIENT_SECRET = "change me for your tigris client secret"
[functions]
  external_node_modules = ["app-root-path", "@tigrisdata/core"]
